bcgov/vue-shared-components

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md

add issue and pr templates

---

src/components/footer/Footer.stories.js
src/components/footer/Footer.stories.mdx
src/components/radio/Radio.css
src/components/radio/Radio.stories.js
src/components/radio/Radio.stories.mdx
src/components/radio/Radio.vue
src/index.js

add radio button component and stories and fix up stories/mdx for footer

add radio button component and stories and fix up stories/mdx for footer

---

src/components/radio/Radio.stories.mdx
src/components/radio/Radio.vue
src/index.js

- add event emission for radio button, try fixing exports
- locally

add event emission for radio button, try fixing exports

---

src/components/callout/Callout.css
src/components/callout/Callout.stories.js
src/components/callout/Callout.stories.mdx
src/components/callout/Callout.vue
src/index.js

- add callout component and story
- local
- storybook

Add callout component and story

---

package.json
src/components/terms-of-use/TermsOfUse.css
src/components/terms-of-use/TermsOfUse.stories.js
src/components/terms-of-use/TermsOfUse.stories.mdx
src/components/terms-of-use/TermsOfUse.vue
src/index.js
src/modules/TermsOfUseTestData.vue
yarn.lock

- Terms of use component
- local
- storybook

Terms of use component

---

src/components/dropdown/Dropdown.css
src/components/dropdown/Dropdown.stories.js
src/components/dropdown/Dropdown.stories.mdx
src/components/dropdown/Dropdown.vue

- Add dropdown component and stories/mdx
- local and storybook

Add dropdown component and stories/mdx

---

src/components/button/Button.css
src/components/button/Button.stories.js
src/components/button/Button.stories.mdx
src/components/button/Button.vue

- Add button component
- local
- storybook

Add button component

---

src/components/sidecard/Sidecard.css
src/components/sidecard/Sidecard.stories.js
src/components/sidecard/Sidecard.stories.mdx
src/components/sidecard/Sidecard.vue

- Add sidecard component
- local
- storybook

Add sidecard component

---

src/components/textarea/Textarea.css
src/components/textarea/Textarea.stories.js
src/components/textarea/Textarea.stories.mdx
src/components/textarea/Textarea.vue

- add textarea component
- local
- storybook

add textarea component

---

src/components/table/Table.css
src/components/table/Table.stories.js
src/components/table/Table.stories.mdx
src/components/table/Table.vue
src/components/table/TableElement.vue
src/modules/tableTestData.js

- Add table and table element components with stories
- storybook

Add table and table element components with stories

---

src/components/display-box/DisplayBox.css
src/components/display-box/DisplayBox.stories.js
src/components/display-box/DisplayBox.stories.mdx
src/components/display-box/DisplayBox.vue
src/modules/DisplayBoxTestData.vue

Display box (part 1)

---

src/components/display-box/DisplayBox.stories.js
src/components/display-box/DisplayBox.stories.mdx
src/components/display-box/DisplayBox.vue

- Add more states to display box

Add more states to display box

---

src/components/alert/Alert.css
src/components/alert/Alert.stories.js
src/components/alert/Alert.stories.mdx
src/components/alert/Alert.vue
src/components/alert/GenerateIcon.vue
src/components/display-box/DisplayBox.stories.js
src/components/display-box/DisplayBox.vue

- Alert component and DisplayBox component fixed using slots
- local and storybook

Alert component and DisplayBox component fixed using slots

---

src/components/input/Input.css
src/components/input/Input.stories.js
src/components/input/Input.stories.mdx
src/components/input/Input.vue

- Add input field component and stories
- local
- storybook

Add input field component and stories

---

src/components/header/Header.vue

Added data binding to `width` attribute in `Header` component
N/A
- [ Y ] Bug fix (non-breaking change which fixes an issue)
Manual tests in private project app.
- [ Y ] My code follows the style guidelines of this project
- [ Y ] I have performed a self-review of my own code
- [ N ] I have made corresponding changes to the documentation
- [ N/A ] New and existing unit tests pass locally with my changes

Added data binding to width attribute in `Header` component.

---

README.md

- Update README with getting started to use release
Please add any relevant UI screenshots of your component(s) or changes to existing component(s).
if your change is a breaking change, please add `breaking change` label to this PR
Please describe the tests that you ran to verify your changes.

Update README with Getting Started

---

package.json
src/AssetsTransformer.js
src/components/footer/Footer.test.js
src/components/footer/__snapshots__/Footer.test.js.snap
yarn.lock

- Add jest to project and initial footer snapshot test(s)
- jest

Add jest to project and initial footer snapshot test(s)

---

.github/workflows/code-climate-test-coverage.yaml
package.json
src/components/table/Table.vue
src/components/table/TableElement.vue
yarn.lock

- Jesting, codecov and code climate
- code climate reports and test coverage working

Jesting, codecov and code climate

---

README.md

- add badges for code climate to readme
- github readme

add badges for code climate to readme

---

package.json
src/components/alert/Alert.test.js
src/components/alert/Alert.vue
src/components/alert/GenerateIcon.vue
src/components/alert/__snapshots__/Alert.test.js.snap
src/components/display-box/DisplayBox.vue
yarn.lock

- Add testing library and alert tests
- adding tests
- jest

Add testing library and alert tests

---

src/components/callout/Callout.test.js
src/components/callout/__snapshots__/Callout.test.js.snap
src/components/loader/Loader.test.js
src/components/loader/__snapshots__/Loader.test.js.snap
src/components/sidecard/Sidecard.test.js
src/components/sidecard/__snapshots__/Sidecard.test.js.snap

- add callout & loader & sidecard tests and snaps
- unit tests
- jest

add callout & loader & sidecard tests and snaps

---

src/components/terms-of-use/TermsOfUse.test.js
src/components/terms-of-use/__snapshots__/TermsOfUse.test.js.snap

add tou test and snaps

---

src/components/header/Header.test.js
src/components/header/__snapshots__/Header.test.js.snap

add header test and snaps

---

package.json

dont test modules cause they are test data

dont test modules cause they are test data

---

src/components/button/Button.test.js
src/components/button/Button.vue
src/components/button/__snapshots__/Button.test.js.snap
src/components/dropdown/Dropdown.test.js
src/components/dropdown/__snapshots__/Dropdown.test.js.snap
src/components/radio/Radio.test.js
src/components/radio/__snapshots__/Radio.test.js.snap

add button & radio & dropdown test and snaps
confirmed working in jest

add button & radio & dropdown test and snaps

---

src/components/input/Input.test.js
src/components/input/__snapshots__/Input.test.js.snap

add input test and snaps
working on jest

add input test and snaps

---

src/components/table/Table.test.js
src/components/table/Table.vue
src/components/table/TableElement.vue
src/components/table/__snapshots__/Table.test.js.snap

add table tests, small modifications to props
tests
jest

add table tests, small modifications to props

---

README.md

add creating a release section to readme

add creating a release section

---

package.json
src/components/footer/Footer.vue
src/components/footer/LinkElement.vue
src/components/footer/__snapshots__/Footer.test.js.snap

- Updated `Footer` component to use `ul` instead of `div` to list the available links.
- Fixed the URL binding.
- Added `update-snapshots` command in `package.json`.
N/A
Yes, using Jest and tested in Storybook.

Updated Footer to use `ul` instead of `div`, and fixed link URL.

---

.github/workflows/deploy-storybook.yml
package.json
yarn.lock

Deploy storybook to github pages
- gh pages

Deploy storybook to github pages

---

package.json

add missing script for deploying storyboook

add missing script

---

src/components/footer/Footer.vue
src/components/footer/__snapshots__/Footer.test.js.snap
src/components/header/Header.vue
src/components/header/HeadingImage.vue
src/components/header/__snapshots__/Header.test.js.snap

Fixes to accessibility when running Axe accessibility analyzer.
N/A
Jest and checked in Storybook.

Fix accessibility issues.

---

package.json
yarn.lock

🤖 Transformers, dependabots in disguise. Transformers, more than meets the eye 👁️

🤖 Transformers, dependabots in disguise

---

package.json
yarn.lock

Transformers, frontend dependabots in disguise 🤖

🤖 Transformers, frontend dependabots in disguise

---

.github/workflows/code-climate-test-coverage.yaml

- {List all the changes, if possible add the jira ticket #}
Please add any relevant UI screenshots of your component(s) or changes to existing component(s).
if your change is a breaking change, please add `breaking change` label to this PR
Please describe the tests that you ran to verify your changes.

Update env in cc gh action
